### ISSUE TITLE
 could not find function "renderEcharts"

### ISSUE THREAD

**Issue by sunshinelu** [yihui/recharts#9]
您好：

  我使用如下命令进行安装recharts，install.packages('recharts',repos = c('http://yihui.name/xran', 'http://cran.rstudio.com'))。安装完毕之后在Rstudio中显示的版本是0.0.1。
   当我运行https://github.com/taiyun/recharts/tree/master/inst/shiny/recharts_shiny_eForce这个网页中的例子时，提示错误“ERROR: could not find function "recharts.shiny.init"”。当不执行命令行“includeHTML(recharts.shiny.init()),”时，提示错误为“Error in (structure(function (input, output)  : 
  could not find function "renderEcharts"“。

我使用的R版本为3.2.2，win7系统64位。

希望您能够帮我解决这个问题，谢谢~

**Comment by yihui** [comment]
这里的recharts和taiyun那边的recharts是两个完全不同的包。要用那边的函数和例子的话，请从那边安装。
